#!/bin/bash
scriptDir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $scriptDir

set -e
# Kills subprocesses on exit
trap "trap - SIGTERM && kill -- -$$ 2>/dev/null" SIGINT SIGTERM EXIT

rush update
if [ ! -z "$(rush list -p | grep " libraries/")" ]; then
  rush build --to-version-policy libraries
fi
if [ ! -z "$(rush list -p | grep " tools/")" ]; then
  rush build --to-version-policy tools
fi

appShortNames="$( \
  rush list --json \
  | grep "\"path\": \"apps/" \
  | awk -F '"' '{print $4}' \
  | awk -F '/' '{print $2}' \
)"

maxShortNameLength=0
serviceCount=0
while IFS= read -r shortName; do
  serviceCount=$((serviceCount + 1))
  shortNameLength=${#shortName}
  if [ $shortNameLength -gt $maxShortNameLength ]; then
    maxShortNameLength=$shortNameLength
  fi
done <<< "$appShortNames"

set -a # automatically export all variables
source .env
set -o xtrace # print out variables as they are set
source common.env
source dev.env
set +o xtrace
set +a

# ASNI escape codes: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
# Original ordering below matches docker compose colors as of v1.26.2 per:
#   https://github.com/docker/compose/blob/master/compose/cli/colors.py
declare -a colorCodes=("36" "33" "32" "35" "34" "36;1" "33;1" "32;1" "35;1" "34;1")
colorCount=${#colorCodes[@]}
# Start at service count to match production colors, since for the production build,
# the static file servers will take the first $serviceCount colors
colorIndex=$serviceCount
while IFS= read -r shortName; do
  colorIndex=$(($colorIndex % $colorCount))
  colorCode=${colorCodes[$colorIndex]}
  colorStart="\033[${colorCode}m"
  colorEnd="\033[0m"
  colorIndex=$(($colorIndex + 1))

  cd "apps/$shortName"
  appTagPrefix="$(printf %-$(($maxShortNameLength))s "$shortName")  | "
  if [ -f "razzle.config.js" ]; then
    envName="$(echo "${shortName//[^[:alnum:]]/_}" | awk '{print toupper($0)}')"
    portName="${envName}_PORT"
    appPort=$(grep "^$portName=" ../../.env | awk -F '=' '{print $2}')
    (PORT=$appPort rushx start | sed -e "s/^/`printf "${colorStart}${appTagPrefix}${colorEnd}"`/") &
  fi
  cd ../..
done <<< "$appShortNames"

wait
